In [1]:
import csv
import numpy as np
import pandas as pd
import scipy.spatial.distance
data = []
data = pd.read_csv("Food rating - Sheet1.csv",header = None)
data = data.loc[:12, 0:18]

In [2]:
data = data[2:11]


In [3]:
data

0                                                  1      2     3    4   \
2   1.0                                            Устрицы     72    85    9   
3   2.0                                     Арахиc соленый    640    69   25   
4   3.0                                       Молоко  2,5%     42   5.9  3.4   
5   4.0                                           Макароны    371    34  3.6   
6   5.0                                Овсяное молоко 3.2%    250     8    1   
7   6.0                                           Шоколад     545   100    5   
8   7.0  Сырок "РОСТАГРОЭКСПОРТ" творожный глазированны...  360.7  35.6  7.7   
9   8.0                                         Кефир 3.2%     57   5.9    3   
10  9.0                                    Гречневая крупа    334     4   12   

      5     6    7    8    9    10 11   12   13   14   15   16   17 18  
2      2   4.4    4  NaN  NaN  NaN  9    5  NaN  NaN  NaN  NaN    3  9  
3     52    17    2    6    4    8  7    4    3    3  NaN    4    6  3  
4    2.5     5    5    1    5    5  4    3    8    4    2    3    5  5  
5    0.4    20    7    7    2    3  2    8    4    6    3    5  NaN  6  
6    3.2   6.5  NaN    2    7    2  6    7    5    5    7  NaN    7  7  
7     33  56.5    3    4    1    9  5  NaN    1    1    6    6    1  2  
8   19.1  39.5  NaN    3    3  NaN  1    2    6    2    1    1    2  8  
9    3.2     4    6    5    8    4  8    1    7    7    4    7  NaN  1  
10     2    67    1    8    6    1  3    6    2    8    5    2    4  4

In [4]:
data1 = data.fillna(1000)
data1 = data1.loc[:,2:18]

In [5]:
data1 = data1.apply(pd.to_numeric) 

In [6]:
data1

2      3     4     5     6     7     8     9     10  11    12    13  \
2    72.0   85.0   9.0   2.0   4.4     4  1000  1000  1000   9     5  1000   
3   640.0   69.0  25.0  52.0  17.0     2     6     4     8   7     4     3   
4    42.0    5.9   3.4   2.5   5.0     5     1     5     5   4     3     8   
5   371.0   34.0   3.6   0.4  20.0     7     7     2     3   2     8     4   
6   250.0    8.0   1.0   3.2   6.5  1000     2     7     2   6     7     5   
7   545.0  100.0   5.0  33.0  56.5     3     4     1     9   5  1000     1   
8   360.7   35.6   7.7  19.1  39.5  1000     3     3  1000   1     2     6   
9    57.0    5.9   3.0   3.2   4.0     6     5     8     4   8     1     7   
10  334.0    4.0  12.0   2.0  67.0     1     8     6     1   3     6     2   

      14    15    16    17  18  
2   1000  1000  1000     3   9  
3      3  1000     4     6   3  
4      4     2     3     5   5  
5      6     3     5  1000   6  
6      5     7  1000     7   7  
7      1     6     6     1   2  
8      2     1     1     2   8  
9      7     4     7  1000   1  
10     8     5     2     4   4

In [7]:
avg = np.array(data1[data1 < 1000].sum())

In [8]:
avg = avg/([9,9,9,9,9,7,8,8,7,9,8,8,8,7,7,7,9])

In [9]:
avg

array([296.85555556,  38.6       ,   7.74444444,  13.04444444,
        24.43333333,   4.        ,   4.5       ,   4.5       ,
         4.57142857,   5.        ,   4.5       ,   4.5       ,
         4.5       ,   4.        ,   4.        ,   4.        ,
         5.        ])

In [10]:
for i in range(17):
    for j in range(9):
        if(data1.iloc[j,i] == 1000):
            data1.iloc[j,i] = avg[i]

In [11]:
data1

2      3     4     5     6    7    8    9         10  11   12   13  \
2    72.0   85.0   9.0   2.0   4.4  4.0  4.5  4.5  4.571429   9  5.0  4.5   
3   640.0   69.0  25.0  52.0  17.0  2.0  6.0  4.0  8.000000   7  4.0  3.0   
4    42.0    5.9   3.4   2.5   5.0  5.0  1.0  5.0  5.000000   4  3.0  8.0   
5   371.0   34.0   3.6   0.4  20.0  7.0  7.0  2.0  3.000000   2  8.0  4.0   
6   250.0    8.0   1.0   3.2   6.5  4.0  2.0  7.0  2.000000   6  7.0  5.0   
7   545.0  100.0   5.0  33.0  56.5  3.0  4.0  1.0  9.000000   5  4.5  1.0   
8   360.7   35.6   7.7  19.1  39.5  4.0  3.0  3.0  4.571429   1  2.0  6.0   
9    57.0    5.9   3.0   3.2   4.0  6.0  5.0  8.0  4.000000   8  1.0  7.0   
10  334.0    4.0  12.0   2.0  67.0  1.0  8.0  6.0  1.000000   3  6.0  2.0   

     14   15   16   17  18  
2   4.5  4.0  4.0  3.0   9  
3   3.0  4.0  4.0  6.0   3  
4   4.0  2.0  3.0  5.0   5  
5   6.0  3.0  5.0  4.0   6  
6   5.0  7.0  4.0  7.0   7  
7   1.0  6.0  6.0  1.0   2  
8   2.0  1.0  1.0  2.0   8  
9   7.0  4.0  7.0  4.0   1  
10  8.0  5.0  2.0  4.0   4

In [12]:
data2 = np.array(data1).astype(np.float)

In [13]:
median = np.mean(data2,axis = 0)
for i in range (17):
    data2[:,i] = data2[:,i] / np.mean(data2[:,i])

In [14]:
median

array([296.85555556,  38.6       ,   7.74444444,  13.04444444,
        24.43333333,   4.        ,   4.5       ,   4.5       ,
         4.57142857,   5.        ,   4.5       ,   4.5       ,
         4.5       ,   4.        ,   4.        ,   4.        ,
         5.        ])

In [35]:
for i in range(12):
    avg[5+i] = 1
ideal = avg/median
ideal

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       0.25      , 0.22222222, 0.22222222, 0.21875   , 0.2       ,
       0.22222222, 0.22222222, 0.22222222, 0.25      , 0.25      ,
       0.25      , 0.2       ])

In [18]:
results = []
for degree in range (11):
    currentresults = []
    for i in range(9):
        currentresults.append( (np.abs(data2[i] - ideal)**(2**(degree - 5))).sum()**(1/(2**(degree - 5))))
    results.append(currentresults)

In [25]:
resultsdata = pd.DataFrame((np.array(results).transpose()/np.mean(results,axis = 1 )).transpose())

In [30]:
resultsdata.columns = list(data[1])
resultsdata = resultsdata.rename({0:-5,1:-4,2:-3,3:-2,4:-1,5:0,6:1,7:2,8:3,9:4,10:5})
resultsdata

Устрицы  Арахиc соленый  Молоко  2,5%  Макароны  Овсяное молоко 3.2%  \
-5  2.318158        2.395216      0.309424  1.668078             2.217465   
-4  2.049682        2.124724      0.720963  1.483985             1.966834   
-3  1.695025        1.768907      0.966475  1.242301             1.636500   
-2  1.408667        1.490976      1.020086  1.057541             1.375792   
-1  1.222610        1.334148      0.993990  0.960719             1.218331   
 0  1.098684        1.280843      0.942155  0.933101             1.127138   
 1  1.005297        1.332519      0.880753  0.941587             1.056874   
 2  0.949031        1.483002      0.833756  0.939699             0.983134   
 3  0.942374        1.618502      0.843973  0.918595             0.923155   
 4  0.941196        1.682662      0.876086  0.903838             0.890642   
 5  0.934372        1.706620      0.888950  0.896687             0.876608   

    Шоколад   Сырок "РОСТАГРОЭКСПОРТ" творожный глазированный с "Варенкой"   \
-5  0.000470                                           0.001865               
-4  0.030479                                           0.037660               
-3  0.216550                                           0.153342               
-2  0.531091                                           0.297169               
-1  0.801900                                           0.422921               
 0  0.969904                                           0.530072               
 1  1.049032                                           0.627256               
 2  1.056396                                           0.712286               
 3  1.024745                                           0.764768               
 4  1.004246                                           0.789586               
 5  1.001916                                           0.800071               

    Кефир 3.2%  Гречневая крупа  
-5    0.052527         0.036798  
-4    0.343387         0.242286  
-3    0.769976         0.550924  
-2    1.048344         0.770334  
-1    1.154974         0.890407  
 0    1.155935         0.962168  
 1    1.099133         1.007550  
 2    1.022113         1.020583  
 3    0.954395         1.009493  
 4    0.913142         0.998602  
 5    0.897574         0.997203

In [31]:
resultsdata.columns = list(data[1])
resultsdata

Устрицы  Арахиc соленый  Молоко  2,5%  Макароны  Овсяное молоко 3.2%  \
-5  2.318158        2.395216      0.309424  1.668078             2.217465   
-4  2.049682        2.124724      0.720963  1.483985             1.966834   
-3  1.695025        1.768907      0.966475  1.242301             1.636500   
-2  1.408667        1.490976      1.020086  1.057541             1.375792   
-1  1.222610        1.334148      0.993990  0.960719             1.218331   
 0  1.098684        1.280843      0.942155  0.933101             1.127138   
 1  1.005297        1.332519      0.880753  0.941587             1.056874   
 2  0.949031        1.483002      0.833756  0.939699             0.983134   
 3  0.942374        1.618502      0.843973  0.918595             0.923155   
 4  0.941196        1.682662      0.876086  0.903838             0.890642   
 5  0.934372        1.706620      0.888950  0.896687             0.876608   

    Шоколад   Сырок "РОСТАГРОЭКСПОРТ" творожный глазированный с "Варенкой"   \
-5  0.000470                                           0.001865               
-4  0.030479                                           0.037660               
-3  0.216550                                           0.153342               
-2  0.531091                                           0.297169               
-1  0.801900                                           0.422921               
 0  0.969904                                           0.530072               
 1  1.049032                                           0.627256               
 2  1.056396                                           0.712286               
 3  1.024745                                           0.764768               
 4  1.004246                                           0.789586               
 5  1.001916                                           0.800071               

    Кефир 3.2%  Гречневая крупа  
-5    0.052527         0.036798  
-4    0.343387         0.242286  
-3    0.769976         0.550924  
-2    1.048344         0.770334  
-1    1.154974         0.890407  
 0    1.155935         0.962168  
 1    1.099133         1.007550  
 2    1.022113         1.020583  
 3    0.954395         1.009493  
 4    0.913142         0.998602  
 5    0.897574         0.997203

In [32]:
df = resultsdata.loc[-5,'Устрицы':'Гречневая крупа']
df.sort_values()

Шоколад                                                          0.000470
Сырок "РОСТАГРОЭКСПОРТ" творожный глазированный с "Варенкой"     0.001865
Гречневая крупа                                                  0.036798
Кефир 3.2%                                                       0.052527
Молоко  2,5%                                                     0.309424
Макароны                                                         1.668078
Овсяное молоко 3.2%                                              2.217465
Устрицы                                                          2.318158
Арахиc соленый                                                   2.395216
Name: -5, dtype: float64

In [33]:
df = resultsdata.loc[0,'Устрицы':'Гречневая крупа']
df.sort_values()

Сырок "РОСТАГРОЭКСПОРТ" творожный глазированный с "Варенкой"     0.530072
Макароны                                                         0.933101
Молоко  2,5%                                                     0.942155
Гречневая крупа                                                  0.962168
Шоколад                                                          0.969904
Устрицы                                                          1.098684
Овсяное молоко 3.2%                                              1.127138
Кефир 3.2%                                                       1.155935
Арахиc соленый                                                   1.280843
Name: 0, dtype: float64

In [34]:
df = resultsdata.loc[5,'Устрицы':'Гречневая крупа']
df.sort_values()

Сырок "РОСТАГРОЭКСПОРТ" творожный глазированный с "Варенкой"     0.800071
Овсяное молоко 3.2%                                              0.876608
Молоко  2,5%                                                     0.888950
Макароны                                                         0.896687
Кефир 3.2%                                                       0.897574
Устрицы                                                          0.934372
Гречневая крупа                                                  0.997203
Шоколад                                                          1.001916
Арахиc соленый                                                   1.706620
Name: 5, dtype: float64

In [33]:
rightrating = [8,9,5,6,7,1,2,4,3]
myrating = data.fillna(1000).loc[:,7]

In [34]:
np.array(myrating).astype(np.int)

array([   4,    2,    5,    7, 1000,    3, 1000,    6,    1])

In [35]:
ans = np.zeros([12])
for k in range (12):
    rightrating = [8,9,5,6,7,1,2,4,3]
    myrating = data.fillna(1000).loc[:,k+7]
    myrating = np.array(myrating).astype(np.int)
    for i in range (9):
        for j in range(9):
            ans[k] = ans[k] + (0 < (myrating[i] - myrating[j]) * (rightrating[i] - rightrating[j]) < 1000)

In [36]:
finalans = ans/np.array([7,8,8,7,9,8,8,8,7,7,7,9])**2

In [262]:
np.argmax(finalans)

10

In [38]:
names = ['Стрижов','Гребенькова','Михеев','Тихонов','Панченко','Панкратов','Харь','Савельев','Исламов','Волынцев','Христолюбов','Алсаханова','Северилов','Колесов','Бишук']

In [39]:
pdf = pd.DataFrame(zip(names,finalans))

In [40]:
pdf

0         1
0       Стрижов  0.530612
1   Гребенькова  0.468750
2        Михеев  0.562500
3       Тихонов  0.489796
4      Панченко  0.617284
5     Панкратов  0.531250
6          Харь  0.531250
7      Савельев  0.500000
8       Исламов  0.489796
9      Волынцев  0.530612
10  Христолюбов  0.775510
11   Алсаханова  0.567901